USER_ICON_RESIZE_WIDTH = 400
USER_ICON_RESIZE_HEIGHT = 400

COMPETITION_OVERALL_RESIZE_WIDTH = 1000
COMPETITION_OVERALL_RESIZE_HEIGHT = 210

NOTEBOOK_IMAGE_UPLOAD = True
NOTEBOOK_IMAGE_WIDTH = 1000
NOTEBOOK_IMAGE_HEIGHT = 1000

SUMMERNOTE_IMAGE_WIDTH = 600